# Generated by Django 5.0.4 on 2024-05-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_digital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
