# Generated by Django 5.0.4 on 2024-05-16 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_digital', '0002_alter_usuario_email_alter_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('favorito', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_digital.usuario')),
            ],
        ),
    ]
