# Generated by Django 5.0.4 on 2024-05-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_digital', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=60, unique=True, verbose_name='Email'),
        ),
    ]
